version: '3.4'
services:
  back-end:
    image: back-end
    container_name: "back-end"
    restart: on-failure
    build:
      context: ./back-end
      dockerfile: ./Dockerfile
    ports:
      - 4000:8080
    command: mvn spring-boot:run
    networks:
      - desafio-vue-network
  front-end:
    image: front-end
    container_name: "front-end"
    restart: on-failure
    environment:
      - API_URL=back-end
    build:
      context: ./front-end/desafio
      dockerfile: ./Dockerfile
    depends_on:
      - back-end
    ports:
      - 5000:80
    networks:
      - desafio-vue-network
networks:
  desafio-vue-network:
    driver: bridge